package billingpackage;
import billingpackage.ConnectionCalss;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
public class AddEmployee extends javax.swing.JFrame {
   
    /**
     * Creates new form Addemployee
     */
    public AddEmployee() {
        initComponents();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        empidlable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namelable = new javax.swing.JLabel();
        emailidlable = new javax.swing.JLabel();
        passwordlable = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        emailidtext = new javax.swing.JTextField();
        empidtext = new javax.swing.JTextField();
        passwordtext = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();
        phonenolable = new javax.swing.JLabel();
        phonenotext = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empidlable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        empidlable.setText("Emp ID");
        jPanel1.add(empidlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel3.setText("ADD EMPLOYEE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 280, -1));

        namelable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        namelable.setText("Name");
        jPanel1.add(namelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, -1));

        emailidlable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        emailidlable.setText("Email");
        jPanel1.add(emailidlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, -1));

        passwordlable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        passwordlable.setText("Password");
        jPanel1.add(passwordlable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, -1));

        nametext.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, -1));

        emailidtext.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        emailidtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailidtextKeyReleased(evt);
            }
        });
        jPanel1.add(emailidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, -1));

        empidtext.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(empidtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 200, -1));

        passwordtext.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        passwordtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordtextKeyReleased(evt);
            }
        });
        jPanel1.add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 200, -1));

        register.setBackground(new java.awt.Color(102, 204, 255));
        register.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 160, -1));

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 90, -1));

        phonenolable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        phonenolable.setText("Phone No.");
        jPanel1.add(phonenolable, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 170, -1));

        phonenotext.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(phonenotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, -1));
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 284, 140, 20));
        jPanel1.add(lbl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 344, 110, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     Admin ad =new Admin();
     ad.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Connection con;
        ConnectionCalss c = new ConnectionCalss();
        try {
            con=c.getCon();
            String sql="INSERT INTO addemployee1(Emp_id,EmpName,Email,Password,Phone_no) values(?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
           
            pst.setString(1,empidtext.getText());
            pst.setString(2,nametext.getText());
            pst.setString(3,emailidtext.getText());
            pst.setString(4,passwordtext.getText());
            pst.setInt(5,Integer.parseInt(phonenotext.getText()));
           
            pst.executeUpdate();  
         JOptionPane.showMessageDialog(null,"insert successfully");
        con.close();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
        }
        empidtext.setText("");
        nametext.setText("");
        emailidtext.setText("");
        passwordtext.setText("");
        phonenotext.setText("");
        
        
        
        
        
    }//GEN-LAST:event_registerActionPerformed

    private void emailidtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailidtextKeyReleased
        String PATTERN="^[a-zA-Z0-9]{0,10}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(emailidtext.getText());
        if(!match.matches())
        {
            lbl_email.setText("Emp ID is incorrect");
        }
        else
        {
            lbl_email.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_emailidtextKeyReleased

    private void passwordtextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordtextKeyReleased
        String PATTERN="^[a-zA-Z0-9]{0,10}$";
        Pattern pat=Pattern.compile(PATTERN);
        Matcher match=pat.matcher(passwordtext.getText());
        if(!match.matches())
        {
            lbl_pass.setText("password is incorrect");
        }
        else
        {
            lbl_pass.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel emailidlable;
    private javax.swing.JTextField emailidtext;
    private javax.swing.JLabel empidlable;
    private javax.swing.JTextField empidtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel namelable;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel passwordlable;
    private javax.swing.JTextField passwordtext;
    private javax.swing.JLabel phonenolable;
    private javax.swing.JTextField phonenotext;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
