package billingpackage;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
public class AddItem extends javax.swing.JFrame {
    String filename=null;
    byte [] chooseimage=null;
    /**
     * Creates new form Additem
     */
    public AddItem() {
        initComponents();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        selectitems = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsarea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        selectimage = new javax.swing.JButton();
        additems = new javax.swing.JButton();
        back = new javax.swing.JButton();
        imagelable = new javax.swing.JLabel();
        discount = new javax.swing.JLabel();
        addisc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setText("ADD ITEM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Item ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Category");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Description");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        itemid.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(itemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 240, -1));

        name.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 240, -1));

        price.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 240, -1));

        selectitems.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        selectitems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Grocery", "Clothes", "Shoes", "Home and Kitchen", "Household Items", "Packed Food", "Beverages" }));
        jPanel1.add(selectitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 240, -1));

        itemsarea.setColumns(20);
        itemsarea.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        itemsarea.setRows(5);
        jScrollPane1.setViewportView(itemsarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 280, 150));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Select Image");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        selectimage.setBackground(new java.awt.Color(102, 204, 255));
        selectimage.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        selectimage.setText("SELECT");
        selectimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectimageActionPerformed(evt);
            }
        });
        jPanel1.add(selectimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, -1, -1));

        additems.setBackground(new java.awt.Color(102, 204, 255));
        additems.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        additems.setText("ADD ITEM");
        additems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additemsActionPerformed(evt);
            }
        });
        jPanel1.add(additems, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, -1, -1));

        imagelable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/unnamed (2).png"))); // NOI18N
        jPanel1.add(imagelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 280, 270));

        discount.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        discount.setText("Discount");
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 30));

        addisc.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        addisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addiscActionPerformed(evt);
            }
        });
        jPanel1.add(addisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 240, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Rs. %");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 50, 30));

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

    Admin ad =new Admin();
     ad.setVisible(true);
     this.setVisible(false);        
// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void selectimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectimageActionPerformed

      JFileChooser choose=new JFileChooser();
      choose.showOpenDialog(null);
      File f =choose.getSelectedFile();
      filename=f.getAbsolutePath();
      ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(imagelable.getWidth(),imagelable.getHeight(),Image.SCALE_SMOOTH));
      imagelable.setIcon(imageicon);
      try{
      File image=new File(filename);
      FileInputStream fis=new FileInputStream(image);
      //LongArrayOutputStream los=new LongArrayOutputStream(); 
      ByteArrayOutputStream bos=new ByteArrayOutputStream();
      byte [] buf=new byte[1024];
      for(int readnum;(readnum=fis.read(buf))!=-1;){
       bos.write(buf,0,readnum);
      
      }
      chooseimage=bos.toByteArray();
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(choose, e);
      
      }
        
        
        
    }//GEN-LAST:event_selectimageActionPerformed

    private void additemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additemsActionPerformed
        
        Connection con;
        ConnectionCalss c = new ConnectionCalss();
        try {
            con=c.getCon();
            String sql="INSERT INTO additem(Item_id,ItemName,Price,Discount,Category,Description,Pictures) values(?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
           
            pst.setString(1,itemid.getText());
            pst.setString(2,name.getText());
            pst.setDouble(3,Double.parseDouble(price.getText()));
            pst.setInt(4, Integer.parseInt(addisc.getText()));
            String items;
            items=selectitems.getSelectedItem().toString();
            pst.setString(5, items);
            
            pst.setString(6,itemsarea.getText());
            pst.setBytes(7,chooseimage);
            pst.executeUpdate();  
         JOptionPane.showMessageDialog(null,"insert successfully");
        con.close();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
        }
        itemid.setText("");
        name.setText("");
        price.setText("");
        addisc.setText("");
        selectitems.setSelectedIndex(0);
        itemsarea.setText("");
        imagelable.setText("");
        
        
        
        
        
        
    }//GEN-LAST:event_additemsActionPerformed

    private void addiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addiscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addisc;
    private javax.swing.JButton additems;
    private javax.swing.JButton back;
    private javax.swing.JLabel discount;
    private javax.swing.JLabel imagelable;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextArea itemsarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JButton selectimage;
    private javax.swing.JComboBox<String> selectitems;
    // End of variables declaration//GEN-END:variables
}
