package billingpackage;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import billingpackage.StartBilling;
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ankit Deswal
 */
public class AddToCart extends javax.swing.JFrame {

    Connection con;
    byte[] chooseimage;

    /**
     * Creates new form Addtocart
     */
    public AddToCart() {
        initComponents();
        showcart();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
    }

    public ArrayList<UserClass> userlist() {//display data in table 
        ArrayList<UserClass> userlist = new ArrayList<>();

        ConnectionCalss c = new ConnectionCalss();
        try {
            con = c.getCon();
            String query = "Select Item_id,Name,Price,Discount,Quantity,Total_Price,Pictures from addtocart";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            UserClass usertb;
            while (rs.next()) {
                usertb = new UserClass(rs.getString("Item_id"), rs.getString("Name"), rs.getDouble("Price"), rs.getInt("Discount"), rs.getInt("Quantity"), rs.getDouble("Total_Price"), rs.getBytes("Pictures"));
                userlist.add(usertb);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
        return userlist;
    }

    public void showcart() {
        ArrayList<UserClass> list = userlist();
        DefaultTableModel model = (DefaultTableModel) carttable.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getitemid();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getprice();
            row[3] = list.get(i).getdiscount();
            row[4] = list.get(i).getquantity();
            row[5] = list.get(i).gettotalprice();
            model.addRow(row);

        }
    }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        fromB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        carttable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addupdate = new javax.swing.JButton();
        adddelete = new javax.swing.JButton();
        makepay = new javax.swing.JButton();
        back = new javax.swing.JButton();
        lblprice = new javax.swing.JLabel();
        number = new javax.swing.JComboBox<>();
        lblimage = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        fromB.setAutoscrolls(true);
        fromB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(775, 533));
        jPanel1.setPreferredSize(new java.awt.Dimension(775, 533));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setText("CART");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        carttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name", "Price", "Discount", "Quantity", "Total Price (Rs.)"
            }
        ));
        carttable.getTableHeader().setReorderingAllowed(false);
        carttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carttableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(carttable);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 470, 260));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Total Price (Rs.)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        addupdate.setBackground(new java.awt.Color(102, 204, 255));
        addupdate.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        addupdate.setText("UPDATE");
        addupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addupdateActionPerformed(evt);
            }
        });
        jPanel1.add(addupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        adddelete.setBackground(new java.awt.Color(102, 204, 255));
        adddelete.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        adddelete.setText("DELETE");
        adddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddeleteActionPerformed(evt);
            }
        });
        jPanel1.add(adddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, -1, -1));

        makepay.setBackground(new java.awt.Color(102, 204, 255));
        makepay.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        makepay.setText("MAKE PAYMENT");
        makepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makepayActionPerformed(evt);
            }
        });
        jPanel1.add(makepay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, -1, -1));

        lblprice.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(lblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 160, 20));

        number.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 150, 30));

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/unnamed (2).png"))); // NOI18N
        jPanel1.add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 250, 260));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        StartBilling st = new StartBilling();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void carttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carttableMouseClicked
        int i = carttable.getSelectedRow();
        TableModel model = carttable.getModel();
        byte[] img = (userlist().get(i).getimage());//display image in table
        ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblimage.getWidth(), lblimage.getHeight(), Image.SCALE_SMOOTH));
        lblimage.setIcon(imageicon);
        chooseimage = img;

    }//GEN-LAST:event_carttableMouseClicked

    private void adddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddeleteActionPerformed
        ConnectionCalss c = new ConnectionCalss();
        try {
            con = c.getCon();
            int row = carttable.getSelectedRow();
            String value = (carttable.getModel().getValueAt(row, 0).toString());
            String sql = "Delete from addtocart where Item_id='" + value + "'";
            Statement pst = con.createStatement();
            pst.executeUpdate(sql);
            DefaultTableModel model = (DefaultTableModel) carttable.getModel();
            model.setRowCount(0);
            showcart();
             //lblimage.setText("");
            JOptionPane.showMessageDialog(null, "successfully");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();

        }
       


    }//GEN-LAST:event_adddeleteActionPerformed

    private void addupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addupdateActionPerformed
        ConnectionCalss c = new ConnectionCalss();
        Integer quantity = Integer.parseInt(number.getSelectedItem().toString());

        try {
            //System.out.println("Inside Update");
            con = c.getCon();
            int row = carttable.getSelectedRow();
            // System.out.println("Inside Update row = "+row);

            String value = (carttable.getModel().getValueAt(row, 0).toString());
            //System.out.println("Value is =  "+value);
            String priceSql = "Select Price,Discount from addtocart where Item_id='" + value + "'";
            PreparedStatement pst = con.prepareStatement(priceSql);
            ResultSet rs = pst.executeQuery();
            rs.next();
            double price = rs.getDouble("Price");
            int disc = rs.getInt("Discount");
            //System.out.println("Inside Update price = "+price);
            String sql = "Update addtocart set Quantity=?, Total_Price=? where Item_id='" + value + "'";
            pst = con.prepareStatement(sql);
            Double totalAmount = ((price * disc )/ 100);
            Double amount = ((price - totalAmount) * quantity);
            pst.setInt(1, quantity);
            pst.setDouble(2, amount);
            double sum=0;
            for(int i=0;i<carttable.getRowCount();i++){
                sum = sum + Double.parseDouble(carttable.getValueAt(i,5).toString());
            
            }
            
            lblprice.setText(Double.toString(sum));
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) carttable.getModel();
            model.setRowCount(0);
            showcart();
            
            JOptionPane.showMessageDialog(null, "succeffuly");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
        


    }//GEN-LAST:event_addupdateActionPerformed

    private void makepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makepayActionPerformed

        Payment py=new Payment();
        py.randomNo();
        Payment.totalBill.setText(this.lblprice.getText());
        py.setVisible(true);
        this.setVisible(false);
       
        
       
        
    }//GEN-LAST:event_makepayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddToCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddelete;
    private javax.swing.JButton addupdate;
    private javax.swing.JButton back;
    public static javax.swing.JTable carttable;
    private javax.swing.JLabel fromB;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblimage;
    public static javax.swing.JLabel lblprice;
    private javax.swing.JButton makepay;
    private javax.swing.JComboBox<String> number;
    // End of variables declaration//GEN-END:variables
}
