/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingpackage;

import static billingpackage.Payment.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
         Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
        
    }

    public void bills()
    {
        Date d=new Date();
      String bilNo=billno.getText();
        String ph = phoneno.getText();
        String pName = pname.getText();
        String balan=txtbalance.getText();
        String pay=txtpayment.getText();
        String total = totalBill.getText();
        String cpay = combox.getSelectedItem().toString();

        AddToCart crt = new AddToCart();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) crt.carttable.getModel();

        Tbill.setText(Tbill.getText() + "------------------------------------------------------------------------------------------------------------------------------------------------\n");

        Tbill.setText(Tbill.getText() + "\t" + "\t"  + " Super Market Bill \n");

        Tbill.setText(Tbill.getText() + "---------------------------------------------------------------------------------------------------------------------------------------------------\n");
        Tbill.setText(Tbill.getText() + "\t\t\t"+"Customer's Details" + "\n");
        Tbill.setText(Tbill.getText() + "Name=" + pName +"\t"+"\t"+"\t"+"\t"+"\t"+"Mobile No ="+ph+"\t"+"\n");
        Tbill.setText(Tbill.getText() + "Total Bill = " + total +"\t\t"+"\t"+"\t"+"Pay By ="+cpay + "\n");
        Tbill.setText(Tbill.getText() + "Date :"+d+"\n");
         Tbill.setText(Tbill.getText() + "Bill No :"+bilNo+"\n");
            
        Tbill.setText(Tbill.getText() + "----------------------------------------------------------------------------------------------------------------------------------------------------------\n");

        Tbill.setText(Tbill.getText() + "Item Id" + "\t" + "Name" + "\t" + "Price" + "\t" + "Discount" + "\t" + "Quantity" + "\t" + "TotalPrice" + "\t");

        for (int i = 0; i < model.getRowCount(); i++) {
            String id = (String) model.getValueAt(i, 0);
            String name = (String) model.getValueAt(i, 1);
            double price = (Double) model.getValueAt(i, 2);
            int discount = (Integer) model.getValueAt(i, 3);
            int quantity = (Integer) model.getValueAt(i, 4);
            double totalprice = (Double) model.getValueAt(i, 5);

            Tbill.setText(Tbill.getText() + "\n" + id + "\t" + name + "\t" + price + "\t" + discount + "\t" + quantity + "\t" + totalprice + "\n");

        }
        Tbill.setText(Tbill.getText() + " \n");
        
        Tbill.setText(Tbill.getText() + " \n");

        Tbill.setText(Tbill.getText() +"\t" + "\t" + "\t" + "\t" + "\t" + "Total Bill : " + total + "\n");
        Tbill.setText(Tbill.getText() +"\t" + "\t" + "\t" + "\t" + "\t" + "Total payment : " + pay + "\n");
        Tbill.setText(Tbill.getText() +"\t" + "\t" + "\t" + "\t" + "\t" + "Balance : " + balan + "\n");

        
        
        
        Tbill.setText(Tbill.getText() + " \n");
        
        Tbill.setText(Tbill.getText() + " \n");
        

        Tbill.setText(Tbill.getText() + "-------------------------------------------------------------------------------------------------------------------------------------------------\n");
        Tbill.setText(Tbill.getText() + "-------------------------------------------------Thank you for Shopping having a good day----------------------------------\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbill = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tbill.setEditable(false);
        Tbill.setColumns(20);
        Tbill.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        Tbill.setRows(5);
        jScrollPane1.setViewportView(Tbill);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Tbill;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
