package billingpackage;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
public class EditItem extends javax.swing.JFrame {
    Connection con;
    String filename;
    byte []chooseimage;
    /**
     * Creates new form Edititem
     */
    public EditItem() {
        this.chooseimage= null;
        initComponents();
        showitems();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
    }
    
    public ArrayList<UserClass>userlist(){//display data in table 
        ArrayList<UserClass>userlist=new ArrayList<>();
       
        ConnectionCalss c = new ConnectionCalss();       
        try {
        con=c.getCon();
        String query="Select Item_id,ItemName, Price,Discount,Category,Description,Pictures from additem";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(query);
        UserClass usertb;
        while(rs.next()){
            usertb=new UserClass(rs.getString("Item_id"),rs.getString("ItemName"),rs.getDouble("Price"),rs.getInt("Discount"),rs.getString("Category"),rs.getString("Description"),rs.getBytes("Pictures"));
            userlist.add(usertb);
        
        }
        
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        return userlist;
    }
    public void showitems(){
    ArrayList<UserClass> list= userlist();
    DefaultTableModel model =(DefaultTableModel)edittable.getModel();
    Object[] row =new Object[8];
    for(int i=0;i<list.size();i++){
        row[0]=list.get(i).getitemid();
        row[1]=list.get(i).getitemname();
        row[2]=list.get(i).getprice();
        row[3]=list.get(i).getdiscount();
        row[4]=list.get(i).getcatagory();
        row[5]=list.get(i).getdescription();
        //row[6]=list.get(i).getimage();
        model.addRow(row);
        
    
    }
    }
    

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        itemid = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        selectitems = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsarea = new javax.swing.JTextArea();
        selectimage = new javax.swing.JButton();
        updateitem = new javax.swing.JButton();
        deleteitems = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        edittable = new javax.swing.JTable();
        imagelable = new javax.swing.JLabel();
        editdisc = new javax.swing.JTextField();
        discount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setMaximumSize(new java.awt.Dimension(1050, 710));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setText("EDIT ITEM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        itemid.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(itemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 210, -1));

        itemname.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(itemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 210, -1));

        price.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 210, -1));

        selectitems.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        selectitems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Grocery", "Clothes", "Shoes", "Home and Kitchen", "Household Items", "Packed Food", "Beverages" }));
        selectitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectitemsActionPerformed(evt);
            }
        });
        jPanel1.add(selectitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 210, -1));

        itemsarea.setColumns(20);
        itemsarea.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        itemsarea.setRows(5);
        jScrollPane2.setViewportView(itemsarea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 210, 110));

        selectimage.setBackground(new java.awt.Color(102, 204, 255));
        selectimage.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        selectimage.setText("SELECT");
        selectimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectimageActionPerformed(evt);
            }
        });
        jPanel1.add(selectimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        updateitem.setBackground(new java.awt.Color(102, 204, 255));
        updateitem.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        updateitem.setText("UPDATE");
        updateitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateitemActionPerformed(evt);
            }
        });
        jPanel1.add(updateitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, -1, -1));

        deleteitems.setBackground(new java.awt.Color(102, 204, 255));
        deleteitems.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        deleteitems.setText("DELETE");
        deleteitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitemsActionPerformed(evt);
            }
        });
        jPanel1.add(deleteitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Item ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Category");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Description");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Select Image");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        edittable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name", "Price", "Discount", "Category", "Description"
            }
        ));
        edittable.getTableHeader().setReorderingAllowed(false);
        edittable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edittableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(edittable);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 620, 140));

        imagelable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/unnamed (2).png"))); // NOI18N
        jPanel1.add(imagelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 280, 290));

        editdisc.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        editdisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdiscActionPerformed(evt);
            }
        });
        jPanel1.add(editdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 210, 30));

        discount.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        discount.setText("Discount");
        jPanel1.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Rs. %");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 805, 735);
    }// </editor-fold>//GEN-END:initComponents

    private void selectimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectimageActionPerformed
        JFileChooser choose=new JFileChooser();
      choose.showOpenDialog(null);
      File f =choose.getSelectedFile();
      filename=f.getAbsolutePath();
      ImageIcon imageicon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(imagelable.getWidth(),imagelable.getHeight(),Image.SCALE_SMOOTH));
      imagelable.setIcon(imageicon);
      try{
      File image=new File(filename);
      FileInputStream fis=new FileInputStream(image);
      ByteArrayOutputStream bos=new ByteArrayOutputStream();
      byte [] buf=new byte[1024];
      for(int readnum;(readnum=fis.read(buf))!=-1;){
       bos.write(buf,0,readnum);
      
      }
      chooseimage=bos.toByteArray();
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(choose, e);
      
      }
        
      
    }//GEN-LAST:event_selectimageActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       Admin ad =new Admin();
        ad.setVisible(true);
        this.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void updateitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateitemActionPerformed
       
         ConnectionCalss c = new ConnectionCalss();
         try {
             con=c.getCon();
             int row =edittable.getSelectedRow();
             System.out.println("value of row:"+row);
             String value =(edittable.getModel().getValueAt(row,0).toString());
             String sql="Update additem set Item_id=? ,ItemName=?, Price=?,Discount=?, Category=?, Description=?,Pictures=? Where Item_id ='"+value+"'";
             PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1,itemid.getText());
             pst.setString(2,itemname.getText());
             pst.setDouble(3,Double.parseDouble(price.getText()));
             pst.setInt(4,Integer.parseInt(editdisc.getText()));
             String items;
             items=selectitems.getSelectedItem().toString();
             pst.setString(5,items);
             pst.setString(6,itemsarea.getText());
             pst.setBytes(7,chooseimage);
             int x=pst.executeUpdate();
             DefaultTableModel model=(DefaultTableModel)edittable.getModel();
             model.setRowCount(0);
             showitems();
             JOptionPane.showMessageDialog(null,"successfully");
              System.out.println(x+"successfully");
                 
             con.close();
         }
         catch(Exception e){
         
             JOptionPane.showMessageDialog(this, e);
             System.out.println(e);
         
         }
         itemid.setText("");
        itemname.setText("");
        price.setText("");
        editdisc.setText("");
        selectitems.setSelectedIndex(0);
        itemsarea.setText("");
        imagelable.setText(null);
        
 
         
         
    }//GEN-LAST:event_updateitemActionPerformed

    private void edittableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edittableMouseClicked
        int i =edittable.getSelectedRow();
        TableModel model=edittable.getModel();
        itemid.setText(model.getValueAt(i, 0).toString());
        itemname.setText(model.getValueAt(i, 1).toString());
        price.setText(model.getValueAt(i, 2).toString());
        editdisc.setText(model.getValueAt(i,3).toString());
 
        String selected=model.getValueAt(i, 4).toString();
        switch(selected){
            case "Grocery":
                selectitems.setSelectedIndex(1);
                break;
            case "Clothes":
                selectitems.setSelectedIndex(2);
                break;
            case "Shoes":
                selectitems.setSelectedIndex(3);
                break;
            case "Home and Kitchen":
                selectitems.setSelectedIndex(4);
                break;
            case "Household Items":
                selectitems.setSelectedIndex(5);
                break;
            case "Packed Food":
                selectitems.setSelectedIndex(6);
                break;
            case "Baverages":
                selectitems.setSelectedIndex(7);
                break;
        }
        itemsarea.setText(model.getValueAt(i, 5).toString());
        byte[] img=(userlist().get(i).getimage());//display image in table
        ImageIcon imageicon=new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imagelable.getWidth(),imagelable.getHeight(),Image.SCALE_SMOOTH));
        imagelable.setIcon(imageicon);
        chooseimage=img;
        
        
        
        
        
        
    }//GEN-LAST:event_edittableMouseClicked

    private void selectitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectitemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectitemsActionPerformed

    private void deleteitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitemsActionPerformed
       ConnectionCalss c = new ConnectionCalss();
         try {
             con=c.getCon();
             int row =edittable.getSelectedRow();
             String value=(edittable.getModel().getValueAt(row, 0).toString());
             String sql="Delete from additem Where Item_id='"+value+"'";
         PreparedStatement pst=con.prepareStatement(sql);
         pst.executeUpdate();
         DefaultTableModel model=(DefaultTableModel)edittable.getModel();
         
         model.setRowCount(0);
             showitems();
             JOptionPane.showMessageDialog(null,"successfully");
         
         
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
             
         
         }
          itemid.setText("");
        itemname.setText("");
        price.setText("");
        editdisc.setText("");
        selectitems.setSelectedIndex(0);
        itemsarea.setText("");
        
        
         
        
        
        
        
        
    }//GEN-LAST:event_deleteitemsActionPerformed

    private void editdiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editdiscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton deleteitems;
    private javax.swing.JLabel discount;
    private javax.swing.JTextField editdisc;
    private javax.swing.JTable edittable;
    private javax.swing.JLabel imagelable;
    private javax.swing.JTextField itemid;
    private javax.swing.JTextField itemname;
    private javax.swing.JTextArea itemsarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField price;
    private javax.swing.JButton selectimage;
    private javax.swing.JComboBox<String> selectitems;
    private javax.swing.JButton updateitem;
    // End of variables declaration//GEN-END:variables
}
