package billingpackage;
import billingpackage.ConnectionCalss;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
public class EditEmployee extends javax.swing.JFrame {
  
    Connection con;
    /**
     * Creates new form Editemployee
     */
    public EditEmployee() {
        initComponents();
        this.setResizable(false);
        showuser();//call method
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
           
    }
    
    public ArrayList<UserClass>userlist() {//display data in table 
        ArrayList<UserClass>userlist=new ArrayList<>();
       
        ConnectionCalss c=new ConnectionCalss();       
        try {
        con=c.getCon();
        String query="Select Emp_id,EmpName,Email,password,Phone_no from addemployee1";
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery(query);
        UserClass usertb;
        while(rs.next()){
            usertb=new UserClass(rs.getString("Emp_id"),rs.getString("EmpName"),rs.getString("Email"),rs.getString("password"),rs.getInt("Phone_no"));
            userlist.add(usertb);
        
        }
        
        }
        catch(Exception e){
        }
        return userlist;
    }
    public void showuser(){
    ArrayList<UserClass> list= userlist();
    DefaultTableModel model =(DefaultTableModel)table.getModel();
    Object[] row =new Object[6];
    for(int i=0;i<list.size();i++){
        
        row[0]=list.get(i).getempid();
        row[1]=list.get(i).getempname();
        row[2]=list.get(i).getemail();
        row[3]=list.get(i).getpassword();
        row[4]=list.get(i).getphoneno();
        model.addRow(row);
        
    
    }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        empid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Search = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        phoneno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(638, 607));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setText("EDIT EMPLOYEE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Emp ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        empid.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 210, -1));

        name.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 210, -1));

        email.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 210, 40));

        Update.setBackground(new java.awt.Color(102, 204, 255));
        Update.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));

        delete.setBackground(new java.awt.Color(102, 204, 255));
        delete.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        back.setBackground(new java.awt.Color(102, 204, 255));
        back.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 580, -1, -1));

        Search.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        Search.setText("Phone No.");
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        table.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Email", "Password", "Phone No."
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 610, 140));

        phoneno.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 210, -1));
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, -1));

        password.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      Admin ad =new Admin();
     ad.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
      
        
         ConnectionCalss c = new ConnectionCalss();
         try {
         
         
             con=c.getCon();
             int row =table.getSelectedRow();
             String value =(table.getModel().getValueAt(row,0).toString());
             String sql="Update addemployee1 set  Emp_id=? , EmpName=?, Email=?, password=?, Phone_no=? Where Emp_id='"+value+"'";
             PreparedStatement pst=con.prepareStatement(sql);
             pst.setString(1,empid.getText());
             pst.setString(2,name.getText());
             pst.setString(3,email.getText());
             pst.setString(4,password.getText());
             pst.setInt(5,Integer.parseInt(phoneno.getText()));
             pst.executeUpdate();
             DefaultTableModel model=(DefaultTableModel)table.getModel();
             model.setRowCount(0);
             showuser();
             JOptionPane.showMessageDialog(null,"successfully");
                 
             con.close();
         }
         catch(Exception e){
         
             JOptionPane.showMessageDialog(null,e);
         System.out.println(e);
         }
         
         empid.setText("");
         name.setText("");
         email.setText("");
         password.setText("");
         phoneno.setText("");
         
         
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       
        int i =table.getSelectedRow();
        TableModel model=table.getModel();
        empid.setText(model.getValueAt(i, 0).toString());
        name.setText(model.getValueAt(i, 1).toString());
        email.setText(model.getValueAt(i, 2).toString());
        password.setText(model.getValueAt(i, 3).toString());
        phoneno.setText(model.getValueAt(i, 4).toString());
        
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         ConnectionCalss c = new ConnectionCalss();
         try {
             con=c.getCon();
             int row =table.getSelectedRow();
             String value=(table.getModel().getValueAt(row, 0).toString());
             String sql="Delete from addemployee1 Where Emp_id='"+value+"'";
         PreparedStatement pst=con.prepareStatement(sql);
         pst.executeUpdate();
         DefaultTableModel model=(DefaultTableModel)table.getModel();
         model.setRowCount(0);
             showuser();
             JOptionPane.showMessageDialog(null,"successfully");
         
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         
         }
         empid.setText("");
         name.setText("");
         email.setText("");
         password.setText("");
         phoneno.setText("");
         
         
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Search;
    private javax.swing.JButton Update;
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneno;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
