package billingpackage;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.awt.print.Printable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
import java.awt.print.PrinterJob;
public class Payment extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
       
    }
    
    public void randomNo(){
        Random rand=new Random();
        int n = rand.nextInt(1000000)+1;
        String val = String.valueOf(n);
        billno.setText(val);
    }    
    
    
     public void bal()
     {
        double tbill=Double.parseDouble(totalBill.getText());
        double pay=Double.parseDouble(txtpayment.getText());
        double bal=(pay-tbill);
        txtbalance.setText(String.valueOf(bal));

        }
     public void print(){
     
     try{
         
            bill.Tbill.print();
            
            }
        catch(PrinterException ep){
            
        
        }
     
     }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        billno = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        payment = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        combox = new javax.swing.JComboBox<>();
        totalBill = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        phoneno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel3.setText("PAYMENT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 240, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("Bill No");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, 20));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 140, 20));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Total Bill");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 228, 160, 20));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Payment Mode");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 180, 30));

        billno.setEditable(false);
        billno.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        billno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billnoActionPerformed(evt);
            }
        });
        billno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                billnoKeyReleased(evt);
            }
        });
        jPanel1.add(billno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 330, 30));

        pname.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 164, 330, 30));

        payment.setBackground(new java.awt.Color(102, 204, 255));
        payment.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        payment.setText("PAYMENT");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 477, 220, 30));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 80, -1));

        combox.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Mode", "Card", "Cash" }));
        jPanel1.add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 397, 330, 30));

        totalBill.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(totalBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 330, 30));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Payment");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 288, 160, 20));

        txtbalance.setEditable(false);
        txtbalance.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jPanel1.add(txtbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 344, 330, 30));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setText("Balance");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 348, 160, 20));

        txtpayment.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        txtpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpaymentKeyReleased(evt);
            }
        });
        jPanel1.add(txtpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 284, 330, 30));

        phoneno.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonenoKeyReleased(evt);
            }
        });
        jPanel1.add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 330, 30));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel9.setText("Phone No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        ConnectionCalss c=new ConnectionCalss();
        try{
            con=c.getCon();
            String sql="insert into Payment(Bill_No,PhoneNo,Name,Total_Bill,Payment_Mode,Customer_pay,Balance)Values(?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,billno.getText());
            pst.setString(2,phoneno.getText());
            pst.setString(3,pname.getText());
            pst.setString(4,totalBill.getText());
            pst.setString(5,combox.getSelectedItem().toString());
            pst.setString(6,txtpayment.getText());
            pst.setString(7, txtbalance.getText());
    
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Successfull Thank you & take out print ");
        
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        
       
       bill b=new bill();
       b.bills();
       b.setVisible(true);
       print();
         StartBilling st=new StartBilling();
         st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_paymentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddToCart cr=new AddToCart();
        cr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void billnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billnoActionPerformed
   
    }//GEN-LAST:event_billnoActionPerformed

    private void billnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billnoKeyReleased
       
    }//GEN-LAST:event_billnoKeyReleased

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void txtpaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaymentKeyReleased
        bal();
    }//GEN-LAST:event_txtpaymentKeyReleased

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void phonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoKeyReleased
        ConnectionCalss c= new ConnectionCalss();
        try{
        
        con=c.getCon();
        String sql="Select PhoneNo,Name from payment where PhoneNo=?";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setString(1,phoneno.getText());
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
         pname.setText(rs.getString("Name"));
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_phonenoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField billno;
    public static javax.swing.JComboBox<String> combox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payment;
    public static javax.swing.JTextField phoneno;
    public static javax.swing.JTextField pname;
    public static javax.swing.JLabel totalBill;
    public static javax.swing.JTextField txtbalance;
    public static javax.swing.JTextField txtpayment;
    // End of variables declaration//GEN-END:variables
}
