package billingpackage;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Deswal
 */
public class StartBilling extends javax.swing.JFrame {
    byte [] chooseimage;
     Connection con;
    /**
     * Creates new form Startbilling
     */
    public StartBilling() {
        this.chooseimage=null;
        initComponents();
        Toolkit tool=getToolkit();
        Dimension size=tool.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        this.setResizable(false);
        
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formA = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        item_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contiue = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        imagelable = new javax.swing.JLabel();
        addtocart = new javax.swing.JButton();
        discount = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        fdisc = new javax.swing.JLabel();
        catagory1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        number = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(862, 680));

        formA.setBackground(new java.awt.Color(51, 255, 255));
        formA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel2.setText("START BILLING");
        formA.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setText("Item ID");
        formA.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        description.setBackground(new java.awt.Color(0, 51, 255));
        description.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        formA.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 210, 170));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setText("Price (Rs.)");
        formA.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel6.setText("Category");
        formA.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setText("Description");
        formA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        item_id.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        item_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_idActionPerformed(evt);
            }
        });
        item_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                item_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                item_idKeyTyped(evt);
            }
        });
        formA.add(item_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setText("Image");
        formA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 80, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setText("Quantity");
        formA.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 130, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel10.setText("Total (Rs.)");
        formA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 170, -1));

        contiue.setBackground(new java.awt.Color(102, 204, 255));
        contiue.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        contiue.setText("CONTINUE");
        contiue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contiueActionPerformed(evt);
            }
        });
        formA.add(contiue, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        formA.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        imagelable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/unnamed (2).png"))); // NOI18N
        formA.add(imagelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 310, 310));

        addtocart.setBackground(new java.awt.Color(102, 204, 255));
        addtocart.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        addtocart.setText("ADD TO CART");
        addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartActionPerformed(evt);
            }
        });
        formA.add(addtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, -1, -1));

        discount.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        discount.setText("Discount");
        formA.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("(Rs. %)");
        formA.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 50, 30));

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel12.setText("Name");
        formA.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        name.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        formA.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 200, 30));

        price.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        formA.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 200, 30));

        fdisc.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        formA.add(fdisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 200, 30));

        catagory1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        formA.add(catagory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 200, 30));
        formA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 690));

        total.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        formA.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 150, 30));

        number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        formA.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 150, 30));

        getContentPane().add(formA, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contiueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contiueActionPerformed
        
        AddToCart ct=new AddToCart();
        ct.setVisible(true);
        this.setVisible(false);
       
       
           
    }//GEN-LAST:event_contiueActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Employee emp=new Employee();
       emp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void item_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_idKeyReleased
       
        ConnectionCalss c= new ConnectionCalss();
        try{
        con=c.getCon();
        String sql="Select itemName,Price,Discount,Category,Description,Pictures from additem where Item_id=?";
        PreparedStatement pst=con.prepareStatement(sql);
        pst.setString(1, item_id.getText());
        ResultSet rs=pst.executeQuery();
        if(rs.next()){
            
            name.setText(rs.getString("itemName"));
            price.setText(rs.getString("Price"));
            fdisc.setText(rs.getString("Discount"));
            catagory1.setText(rs.getString("Category"));
            description.setText(rs.getString("Description"));
            byte [] img=rs.getBytes("Pictures");
            ImageIcon imageicon=new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(imagelable.getWidth(),imagelable.getHeight(),Image.SCALE_SMOOTH));
            imagelable.setIcon(imageicon);
            chooseimage=img;  
        }
        con.close();
        }
        catch(Exception e){
        
        }
        
        
    }//GEN-LAST:event_item_idKeyReleased

    private void item_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_idKeyTyped
     
    }//GEN-LAST:event_item_idKeyTyped

    private void addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartActionPerformed

       
        ConnectionCalss c= new ConnectionCalss();
        try{
        con=c.getCon();
          String sql="INSERT INTO addtocart(Item_id,Name,Price,Discount,Quantity,Total_Price,Pictures) values(?,?,?,?,?,?,?)";
           PreparedStatement pst=con.prepareStatement(sql);
           
            pst.setString(1,item_id.getText());
            pst.setString(2,name.getText());
            pst.setDouble(3,Double.parseDouble(price.getText()));
            pst.setInt(4,Integer.parseInt(fdisc.getText()));
            pst.setInt(5,Integer.parseInt(number.getSelectedItem().toString()));
            
            pst.setDouble(6,Double.parseDouble(total.getText()));
            pst.setBytes(7,chooseimage);
            pst.executeUpdate();  
         JOptionPane.showMessageDialog(null,"insert successfully");
        con.close();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
        }   
    }//GEN-LAST:event_addtocartActionPerformed

    private void item_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_idActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
      Double price1=Double.parseDouble(price.getText());
      Integer dis=Integer.parseInt(fdisc.getText());
      Integer to=Integer.parseInt(number.getSelectedItem().toString());
      Double countdisc=(price1*dis/100);
      
      Double tprice=((price1-countdisc)*to);
      total.setText(tprice.toString());
        
    }//GEN-LAST:event_numberActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocart;
    private javax.swing.JLabel catagory1;
    private javax.swing.JButton contiue;
    private javax.swing.JLabel description;
    private javax.swing.JLabel discount;
    private javax.swing.JLabel fdisc;
    private javax.swing.JPanel formA;
    private javax.swing.JLabel imagelable;
    private javax.swing.JTextField item_id;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> number;
    private javax.swing.JLabel price;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
